apiVersion: v1
kind: Service
metadata:
  labels:
    run: labapp-api
  name: labapp-api
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    run: labapp-api
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: labapp-api
  name: labapp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      run: labapp-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: labapp-api
    spec:
      containers:
      - image: {{.Values.registry}}/{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
{{ if .Values.api.connectionString }}
        env:
        - name: DB_CONNECTION_STRING
          value: {{.Values.api.connectionString}}
{{ else }}
        env:
        - name: DB_CONNECTION_STRING
          value: "Data Source=db;Initial Catalog=master;User Id=sa;Password=P2ssw0rd"
{{ end }}
        imagePullPolicy: Always
        name: labapp-api
        resources:
          limits:
            memory: 200Mi
            cpu: "0.4" 